- hosts: [mesos_masters]
  sudo: True
  tasks: 
    - name: Install vim
      apt: pkg={{ item }} state=present
      with_items:
        - git
        - vim
  roles:
    - { role: './librarian_roles/ansible-docker', tags:['os-tools'] }
    - { role: './librarian_roles/ansible-java8', tags:['runtimes', 'java']}
    - { role: './librarian_roles/info.haproxy' }
    - { role: './librarian_roles/ansible-mesos', mesos_cluster_name: "mlh_mesos", mesos_options: "--log_dir=$LOGS", tags: ['mesos', 'platforms'] }
    - { role: './librarian_roles/ansible-marathon', tags:['mesos-tools'] }

- hosts: [mesos_slaves]
  sudo: True
  roles: 
    - { role: './librarian_roles/ansible-docker', tags:['os-tools'] }
    - { role: './librarian_roles/ansible-java8', tags:['runtimes', 'java']}
    - { role: './librarian_roles/ansible-mesos', mesos_install_mode: "slave", mesos_version: "0.19.0", mesos_options: "--log_dir=$LOGS", tags: ['mesos', 'platforms'] }
